# Étape 1 : Utiliser une image de base Node.js
FROM node:lts-alpine as build-stage

LABEL description="Development image for the library MERN API"

# Étape 2 : Définir le répertoire de travail à l'intérieur du conteneur
WORKDIR /app

# Étape 3 : Copier les fichiers package.json et package-lock.json
# Ceci permettra d'installer les dépendances avant de copier le reste des fichiers,
# afin de profiter du cache des dépendances lors des builds ultérieurs.
COPY ["package*.json", "package-lock.json", "npm-shrinkwrap.json*", "./"]

# Étape 4 : Installer les dépendances
RUN npm install && npm cache clean --force

# Étape 5 : Copier le reste des fichiers de l'application
COPY . .

EXPOSE 5000

cmd ["npm", "run", "dev"]